### ISSUE TITLE
Errors in code?

### ISSUE THREAD

**Issue by VincxBlox** [Nicolas-Gatien/MUSE#7]
I ran "main.py" and just gets this. I tryed installing pyttsx3, but it says no module for speech regnoziement (spelt that wrong). you are missing text saying what dependencies we need. How do we change how to modify to API key to actually use it?

C:\Users\Vince>C:\Users\Vince\Downloads\MUSE-main\MUSE-main\main.py
Traceback (most recent call last):
  File "C:\Users\Vince\Downloads\MUSE-main\MUSE-main\main.py", line 5, in <module>
    import pyttsx3
ModuleNotFoundError: No module named 'pyttsx3'

C:\Users\Vince>pip install pyttsx3
Collecting pyttsx3
  Downloading pyttsx3-2.90-py3-none-any.whl (39 kB)
Collecting comtypes (from pyttsx3)
  Downloading comtypes-1.2.0-py2.py3-none-any.whl (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 5.4 MB/s eta 0:00:00
Collecting pypiwin32 (from pyttsx3)
  Downloading pypiwin32-223-py3-none-any.whl (1.7 kB)
Collecting pywin32 (from pyttsx3)
  Downloading pywin32-306-cp311-cp311-win_amd64.whl (9.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 5.0 MB/s eta 0:00:00
Installing collected packages: pywin32, comtypes, pypiwin32, pyttsx3
Successfully installed comtypes-1.2.0 pypiwin32-223 pyttsx3-2.90 pywin32-306

C:\Users\Vince>C:\Users\Vince\Downloads\MUSE-main\MUSE-main\main.py
Traceback (most recent call last):
  File "C:\Users\Vince\Downloads\MUSE-main\MUSE-main\main.py", line 6, in <module>
    import speech_recognition as sr
ModuleNotFoundError: No module named 'speech_recognition'

**Comment by Nicolas-Gatien** [comment]
Make sure you pip install the modules: pyttsx3 and speech_recognition
Also, make sure you downloaded MUSE mk2 - the current repo is kind of broken.
About to revert some changes because I now realize I forgot to make a new branch.

Closing the issue, let me know if you have any other questions and then I'll open it back up.

**Comment by VincxBlox** [comment]
"speech_recognition" simply doesn't exist

**Comment by Nicolas-Gatien** [comment]
```pip install SpeechRecognition```

**Comment by VincxBlox** [comment]
there is TONS of package that needed to be manually installed, and now you didnt say where to put our api keys so it works. Please tell me.

**Comment by Nicolas-Gatien** [comment]
Yeah - this is very much still in the prototype phase.
The OpenAI API key should be in config/api_keys.json. That file should have this format:
{
    "openai": "YOUR-API-KEY",
}
The GMAIL commands take a LOT more work to set up. I'll make a PDF guide at some point for it.
Let me know if it works now :D

**Comment by VincxBlox** [comment]
So you create the folder?

**Comment by Nicolas-Gatien** [comment]
Yep!
Create a folder called config.
Then create a file called api_keys.json

**Comment by VincxBlox** [comment]
The json file needs to be called "my_api_keys", not "api_keys" and i also get this when opening it

Traceback (most recent call last):
  File "C:\Users\Vince\Downloads\MUSE-main\MUSE-main\main.py", line 50, in <module>
    command_objs = load_command_objects()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vince\Downloads\MUSE-main\MUSE-main\main.py", line 26, in load_command_objects
    command_objs.append(obj())
                        ^^^^^
  File "C:\Users\Vince\Downloads\MUSE-main\MUSE-main\commands\add_command.py", line 25, in __init__
    super().__init__(f"{self.name}", self.metadata)
  File "C:\Users\Vince\Downloads\MUSE-main\MUSE-main\commands\base_command.py", line 6, in __init__
    self.keys = json.load(f)
                ^^^^^^^^^^^^
  File "C:\Users\Vince\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Vince\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vince\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vince\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 3 column 1 (char 67)

**Comment by Nicolas-Gatien** [comment]
Don't know how to fix this.

**Comment by 99letters** [comment]
Hi ! Nicolas!!
'config\\api_keys.json not found. Do I need to create these folders myself?

例外が発生しました: FileNotFoundError
[Errno 2] No such file or directory: 'config\\api_keys.json'
  File "C:\Users\391471_black\Desktop\python\MUSE-mk2\main.py", line 38, in <module>
    with open("config\\api_keys.json") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\api_keys.json'

**Comment by Nicolas-Gatien** [comment]
Yep, you need to create the config folder, then the api_keys.json and put your own API key in there. It should look like:

{
"openai": "YOUR-API-KEY"
}

**Comment by 99letters** [comment]
wow! Thanks @Nicolas-Gatien !!

**Comment by 99letters** [comment]
@Nicolas-Gatien  bro.

The following problem occurred.


    while True:
            response = openai.ChatCompletion.create(
            
 APIRemovedInV1


You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`


What should I do about this?
Update your code to the latest openai interface: Use the latest version of the openai library (1.0.0 or later) and update your code. This requires consulting the openai documentation (OpenAI Python GitHub) and making the necessary changes. You can also run the command openai migrate to automatically upgrade your codebase.

Use an older version of Openai: If you want to use your current code without modification, install an older version of the Openai library (e.g. 0.28).

**Comment by 99letters** [comment]
@Nicolas-Gatien pip install openai==0.28 in current situation
After that, we were able to have a conversation on the computer. This is great. It would be even better if you could make it possible with GPT4.
Also, when I upgraded Python to 3.9 or higher, I was unable to install some modules. I would appreciate it if you could write it down in a memo etc.

**Comment by Nicolas-Gatien** [comment]
Hey! Yeah this is a bit of an old repo, haven't done much on it.
Check out the "DigitalAssistant" repo instead, it's an updated version of this prototype.
Unfortunately no memo though, which modules can't you install?
